import React from 'react'
import type { Metadata } from 'next'
import { Be_Vietnam_Pro } from 'next/font/google'
import { cookies } from 'next/headers'

import Footer from '@/components/layout/footer'
import Header from '@/components/layout/header'
import { getDictionary } from '@/dictionaries/get-dictionary'
import DictionaryProvider from '@/providers/dictionary-provider'
import ThemeProvider from '@/providers/theme-provider'
import { StoreKeys } from '@/stores/store-keys'
import { DefaultPageProps } from '@/types/common'
import { cn } from '@/utils/cn'

import './globals.scss'

const beVietNamPro = Be_Vietnam_Pro({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--be-vietnam-pro',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
  params,
}: React.PropsWithChildren<DefaultPageProps>) {
  const authenticationButtonTab = cookies().get(StoreKeys.AuthenticationButtonTab)
  const dictionary = await getDictionary(params.lang)

  console.log(`🆘 src/app/[lang]/layout.tsx`) // eslint-disable-line
  console.log(dictionary) // eslint-disable-line
  console.log('%c => dictionary ', 'background: #0095FF; color: #fff') // eslint-disable-line
  console.log(new Date()) // eslint-disable-line

  return (
    <html lang="en">
      <body
        className={cn(
          beVietNamPro.className,
          beVietNamPro.variable,
          'flex min-h-screen flex-col bg-dark-background antialiased',
        )}
      >
        <main className="flex h-full flex-1 flex-col">
          <DictionaryProvider dictionary={dictionary}>
            <ThemeProvider>
              <Header authenticationButtonTab={authenticationButtonTab} />
              <div className="flex flex-1 flex-col">{children}</div>
              <Footer acceptHidden />
            </ThemeProvider>
          </DictionaryProvider>
        </main>
      </body>
    </html>
  )
}
